/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

const BASE_API_URL = 'https://api.voicenotes.com/api/integrations/obsidian-sync';
const API_ROUTES = {
    GET_USER: '/user/info',
    GET_VOICE_NOTE_URL: '/voicenotes',
    GET_VOICE_NOTE_SIGNED_URL: '/voicenotes/signed-url',
    GET_RECORDINGS: '/recordings',
    DELETE_RECORDING: '/recordings/:recordingId',
    GET_SIGNED_URL: '/recordings/:recordingId/signed-url',
};

class VoiceNotesApi {
    constructor(options = {}) {
        this.deletedLocalRecordingIds = [];
        this.filterTags = [];
        this.tagFilterMode = 'exclude';
        if (options.token) {
            this.token = options.token;
        }
        if (options.lastSyncedNoteUpdatedAt) {
            this.lastSyncedNoteUpdatedAt = options.lastSyncedNoteUpdatedAt;
        }
        if (options.deletedLocalRecordingIds) {
            this.deletedLocalRecordingIds = options.deletedLocalRecordingIds;
        }
        if (options.filterTags) {
            this.filterTags = options.filterTags;
        }
        if (options.tagFilterMode) {
            this.tagFilterMode = options.tagFilterMode;
        }
    }
    setToken(token) {
        this.token = token || undefined;
    }
    /**
     * Validates if a token exists and is non-empty
     */
    hasValidToken() {
        return !!(this.token && this.token.trim().length > 0);
    }
    /**
     * Builds the full API URL from an endpoint
     */
    buildUrl(endpoint) {
        // Handle full URLs (for pagination links that come back from API)
        if (endpoint.startsWith('http://') || endpoint.startsWith('https://')) {
            return endpoint;
        }
        // Ensure endpoint starts with /
        const cleanEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
        return `${BASE_API_URL}${cleanEndpoint}`;
    }
    /**
     * Sleep utility for rate limit backoff
     */
    async sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    /**
     * Makes an authenticated request with consistent error handling and rate limit retry logic
     */
    async makeAuthenticatedRequest(endpoint, options = {}, retryCount = 0) {
        if (!this.hasValidToken()) {
            throw new Error('No valid authentication token');
        }
        const url = this.buildUrl(endpoint);
        const headers = {
            Authorization: `Bearer ${this.token}`,
            'X-API-KEY': `${this.token}`,
        };
        // Merge in any additional headers from options
        if (options.headers) {
            const optHeaders = options.headers;
            Object.assign(headers, optHeaders);
        }
        const res = await obsidian.requestUrl({
            url,
            method: options.method || 'GET',
            headers,
            body: options.body,
            throw: false,
        });
        if (res.status >= 200 && res.status < 300) {
            return res.json;
        }
        if (res.status === 401) {
            this.token = undefined;
            throw {
                status: res.status,
                message: 'Authentication failed - token invalid or expired',
            };
        }
        if (res.status === 404) {
            throw {
                status: res.status,
                message: 'Resource not found, Please try again later',
            };
        }
        if (res.status === 400) {
            const errorData = res.json;
            const message = errorData.message || 'Bad Request';
            new obsidian.Notice(message || 'Bad Request');
            throw {
                status: res.status,
                message: message || 'Bad Request',
            };
        }
        // Handle Laravel rate limiting (429 Too Many Requests)
        if (res.status === 429) {
            const maxRetries = 3;
            if (retryCount >= maxRetries) {
                throw {
                    status: res.status,
                    message: 'Rate limit exceeded. Please try again later.',
                };
            }
            // Check for Retry-After header (Laravel provides this)
            const retryAfter = res.headers['retry-after'];
            let waitTime;
            if (retryAfter) {
                const parsed = parseInt(retryAfter, 10) + 1;
                console.log(`Rate limited. Retry-After header: ${retryAfter}s`);
                // Use server value but fall back to exponential backoff if 0 or invalid
                waitTime = parsed > 0 ? parsed * 1000 : Math.pow(2, retryCount) * 1000;
            }
            else {
                // Exponential backoff: 2^retryCount seconds
                waitTime = Math.pow(2, retryCount) * 1000;
            }
            // Cap wait time at 60 seconds
            waitTime = Math.min(waitTime, 60000);
            console.log(`Rate limited. Waiting ${waitTime / 1000} seconds before retry ${retryCount + 1}/${maxRetries}...`);
            new obsidian.Notice(`Rate limited. Retrying in ${Math.ceil(waitTime / 1000)} seconds...`);
            await this.sleep(waitTime);
            return this.makeAuthenticatedRequest(endpoint, options, retryCount + 1);
        }
        throw {
            status: res.status,
            message: 'Something went wrong, Please try again later',
        };
    }
    async getSignedUrl(recordingId) {
        if (!this.hasValidToken()) {
            return null;
        }
        try {
            const data = await this.makeAuthenticatedRequest(API_ROUTES.GET_SIGNED_URL.replace(':recordingId', recordingId));
            return data;
        }
        catch (error) {
            console.error('Failed to get signed URL:', error);
            throw error;
        }
    }
    async downloadFile(fs, url, outputLocationPath) {
        try {
            const response = await obsidian.requestUrl({ url });
            await fs.writeBinary(outputLocationPath, response.arrayBuffer);
        }
        catch (error) {
            console.error('Failed to download file:', error);
            throw error;
        }
    }
    async deleteRecording(recordingId) {
        if (!this.hasValidToken()) {
            return false;
        }
        const response = await this.makeAuthenticatedRequest(API_ROUTES.DELETE_RECORDING.replace(':recordingId', recordingId), {
            method: 'DELETE',
        });
        return response;
    }
    async getRecordingsFromLink(link) {
        if (!this.hasValidToken()) {
            return null;
        }
        try {
            const options = {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
            };
            // This uses the full link URL (for pagination)
            const data = await this.makeAuthenticatedRequest(link, options);
            return data;
        }
        catch (error) {
            console.error('Failed to get recordings from link:', error);
            throw error;
        }
    }
    async getRecordings() {
        if (!this.hasValidToken()) {
            return null;
        }
        try {
            const options = {
                body: JSON.stringify({
                    obsidian_deleted_recording_ids: this.deletedLocalRecordingIds,
                    last_synced_note_updated_at: this.lastSyncedNoteUpdatedAt,
                    filter_tags: this.filterTags,
                    tag_filter_mode: this.tagFilterMode,
                }),
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
            };
            const data = await this.makeAuthenticatedRequest(API_ROUTES.GET_RECORDINGS, options);
            return data;
        }
        catch (error) {
            console.error('Failed to get recordings:', error);
            throw error;
        }
    }
    async getUserInfo() {
        if (!this.hasValidToken()) {
            return null;
        }
        try {
            const data = await this.makeAuthenticatedRequest(API_ROUTES.GET_USER);
            return data;
        }
        catch (error) {
            console.error('Failed to get user info:', error);
            // Don't throw here as this is used to check if token is valid
            return null;
        }
    }
}

class DateTimeHelper {
    static isToday(date) {
        // @ts-expect-error - moment is callable despite TypeScript thinking otherwise
        return obsidian.moment(date).isSame(obsidian.moment(), 'day');
    }
    static formatDate(date, dateFormat) {
        try {
            // @ts-expect-error - moment is callable despite TypeScript thinking otherwise
            return obsidian.moment(date).format(dateFormat);
        }
        catch (error) {
            console.error('Error formatting date:', error);
            return date;
        }
    }
    static formatDuration(durationMs) {
        const minutes = Math.floor(durationMs / 60000);
        const seconds = Math.floor((durationMs % 60000) / 1000);
        if (minutes > 0) {
            return `${minutes}m${seconds.toString().padStart(2, '0')}s`;
        }
        else {
            return `${seconds}s`;
        }
    }
}

class AppHelper {
    static autoResizeTextArea(textarea) {
        requestAnimationFrame(() => {
            textarea.style.height = 'auto';
            textarea.style.height = `${textarea.scrollHeight}px`;
        });
    }
}

class FileHelper {
    static getFilenameFromUrl(url) {
        try {
            const parsedUrl = new URL(url);
            const pathname = parsedUrl.pathname;
            const filename = pathname.split('/').pop();
            return filename || '';
        }
        catch (error) {
            console.error('Invalid URL:', error);
            return '';
        }
    }
    static convertHtmlToMarkdown(text) {
        const htmlEntities = {
            '&lt;': '<',
            '&gt;': '>',
            '&amp;': '&',
            '&quot;': '"',
            '&#39;': "'",
            '&nbsp;': ' ',
        };
        // Convert HTML entities
        let markdown = text.replace(/&[a-zA-Z0-9#]+;/g, (entity) => htmlEntities[entity] || entity);
        // Convert <br/> tags to newlines
        markdown = markdown.replace(/<br\s*\/?>/gi, '\n');
        // Remove other HTML tags
        markdown = markdown.replace(/<\/?[^>]+(>|$)/g, '');
        return markdown.trim();
    }
}

class VoiceNotesSettingTab extends obsidian.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
        this.vnApi = new VoiceNotesApi({});
    }
    async display() {
        const { containerEl } = this;
        containerEl.empty();
        this.renderHeader(containerEl);
        if (!this.getSetting('token')) {
            await this.renderLoginSection(containerEl);
            return;
        }
        this.vnApi.setToken(this.getSetting('token'));
        // Use cached user info to avoid API call on every settings open
        let userInfo = this.getSetting('cachedUserInfo');
        if (!userInfo) {
            userInfo = await this.vnApi.getUserInfo();
            if (userInfo) {
                await this.setSetting('cachedUserInfo', userInfo);
            }
        }
        await this.renderUserSection(containerEl, userInfo);
        await this.renderSyncSettings(containerEl);
        await this.renderContentSettings(containerEl);
        await this.renderTemplateSettings(containerEl);
        await this.renderAdvancedSettings(containerEl);
    }
    renderHeader(containerEl) {
        const header = containerEl.createDiv({
            attr: { style: 'display:flex; align-items:center; gap:8px; margin-bottom:10px' },
        });
        header.createEl('h1', { text: 'Voicenotes Settings' });
        header.createSpan({
            text: `v${this.plugin.manifest.version}`,
            cls: 'txt-muted',
        });
    }
    async renderLoginSection(containerEl) {
        var _a;
        const wrapper = containerEl.createDiv();
        wrapper.createEl('h2', {
            text: 'Connect your account',
            attr: { style: 'margin-bottom: 4px;' },
        });
        wrapper.createEl('p', {
            text: 'Start syncing your voice notes by connecting your account using an authentication token.',
            cls: 'txt-muted',
            attr: { style: 'margin-bottom: 13px; margin-top: 0;' },
        });
        const inputEl = wrapper.createEl('input', {
            type: 'password',
            placeholder: 'Enter your Voicenotes Auth Token',
            cls: 'auth-input',
        });
        inputEl.value = String((_a = this.getSetting('token')) !== null && _a !== void 0 ? _a : '');
        inputEl.addEventListener('input', async (event) => {
            const target = event.target;
            await this.setSetting('token', target.value);
        });
        const btnWrapper = wrapper.createDiv({ cls: 'btn-wrapper' });
        const button = btnWrapper.createEl('button', {
            text: 'Connect',
            cls: 'mod-cta auth-btn',
        });
        button.addEventListener('click', async () => await this.handleLogin());
        const extButton = btnWrapper.createEl('button', {
            cls: 'btn-secondary auth-btn external-btn',
            text: 'Get your token',
        });
        extButton.addEventListener('click', () => {
            window.open('https://voicenotes.com/app?obsidian=true#settings', '_blank');
        });
        const externalIcon = extButton.createDiv();
        obsidian.setIcon(externalIcon, 'external-link');
    }
    async renderUserSection(containerEl, userInfo) {
        const userRow = containerEl.createDiv({
            cls: 'user-row',
        });
        const userInline = userRow.createDiv({ attr: { style: 'display:flex;align-items:center;gap:10px' } });
        const initials = (userInfo.name || '')
            .split(' ')
            .map((p) => p[0])
            .join('')
            .slice(0, 2)
            .toUpperCase() || '?';
        userInline.createDiv({
            text: initials,
            cls: 'user-initials',
        });
        const txt = userInline.createDiv({ attr: { style: 'line-height:1' } });
        txt.createEl('div', { text: `Signed in as ${userInfo.name}`, attr: { style: 'font-weight:600' } });
        txt.createEl('div', {
            text: `${userInfo.email}`,
            cls: 'txt-muted',
        });
        const userActions = userRow.createDiv({ attr: { style: 'display:flex;align-items:center;gap:10px' } });
        const syncBtn = userActions.createEl('button', {
            cls: 'mod-cta sync-btn',
            attr: {
                title: 'Manually sync your voice notes now',
            },
        });
        syncBtn.createEl('span', {
            text: 'Sync Now',
            cls: 'sync-btn-label',
        });
        const dotsContainer = syncBtn.createEl('span', {
            cls: 'sync-dots',
            attr: { style: 'display:none' },
        });
        dotsContainer.createEl('span', { cls: 'dot' });
        dotsContainer.createEl('span', { cls: 'dot' });
        dotsContainer.createEl('span', { cls: 'dot' });
        syncBtn.addEventListener('click', async () => await this.handleSync());
        const btn = userActions.createEl('button', {
            text: 'Logout',
            cls: 'btn-bordered',
            attr: {
                title: 'Logout from VoiceNotes',
            },
        });
        btn.addEventListener('click', async () => await this.handleLogout());
    }
    async renderSyncSettings(containerEl) {
        new obsidian.Setting(containerEl).setName('Sync Settings').setHeading();
        new obsidian.Setting(containerEl)
            .setName('Automatic sync')
            .setDesc('Enable automatic syncing of voice notes at regular intervals')
            .addDropdown((dropdown) => {
            var _a;
            const options = {
                '60': 'Every 1 hour',
                '180': 'Every 3 hours',
                '360': 'Every 6 hours',
                '720': 'Every 12 hours',
                '1440': 'Every day',
            };
            const current = String((_a = this.getSetting('syncTimeout')) !== null && _a !== void 0 ? _a : 30);
            if (!options[current]) {
                options[current] = `${current} minutes`;
            }
            dropdown
                .addOptions(options)
                .setValue(current)
                .onChange(async (value) => {
                await this.setSetting('syncTimeout', Number(value));
            });
            dropdown.setDisabled(!this.getSetting('automaticSync'));
            return dropdown;
        })
            .addToggle((toggle) => {
            var _a;
            return toggle.setValue((_a = this.getSetting('automaticSync')) !== null && _a !== void 0 ? _a : false).onChange(this.createToggleHandler('automaticSync', async () => {
                if (this.getSetting('automaticSync')) {
                    await this.plugin.sync();
                }
                await this.display();
            }));
        });
        new obsidian.Setting(containerEl)
            .setName('Sync directory')
            .setDesc('Directory within your vault where notes will be synced')
            .addText((text) => {
            var _a;
            return text
                .setPlaceholder('voicenotes')
                .setValue((_a = this.getSetting('syncDirectory')) !== null && _a !== void 0 ? _a : '')
                .onChange(this.createTextInputHandler('syncDirectory'));
        });
        const isIncludeMode = this.getSetting('tagFilterMode') === 'include';
        new obsidian.Setting(containerEl)
            .setName('Tag Filter')
            .setDesc(isIncludeMode
            ? 'Only sync notes with these tags (comma-separated)'
            : 'Skip notes with these tags (comma-separated)')
            .addDropdown((dropdown) => {
            var _a;
            return dropdown
                .addOption('exclude', 'Exclude')
                .addOption('include', 'Include')
                .setValue((_a = this.getSetting('tagFilterMode')) !== null && _a !== void 0 ? _a : 'exclude')
                .onChange(async (value) => {
                await this.setSetting('tagFilterMode', value);
                await this.display();
            });
        })
            .addText((text) => {
            var _a;
            return text
                .setPlaceholder(isIncludeMode ? 'work, important' : 'archive, trash')
                .setValue(((_a = this.getSetting('excludeTags')) !== null && _a !== void 0 ? _a : []).join(', '))
                .onChange(async (value) => {
                const tags = value.split(',').map((t) => t.trim()).filter((t) => t.length > 0);
                await this.setSetting('excludeTags', tags);
                // Reset lastSyncedNoteUpdatedAt when tags change so filtered notes can be re-evaluated
                await this.setSetting('lastSyncedNoteUpdatedAt', null);
            });
        });
    }
    async renderContentSettings(containerEl) {
        new obsidian.Setting(containerEl).setName('Notes Settings').setHeading();
        new obsidian.Setting(containerEl)
            .setName('Add a tag to todos')
            .setDesc('When syncing a note add an optional tag to the todo')
            .addText((text) => {
            var _a;
            return text
                .setPlaceholder('TODO')
                .setValue((_a = this.getSetting('todoTag')) !== null && _a !== void 0 ? _a : '')
                .onChange(this.createTextInputHandler('todoTag'));
        });
        new obsidian.Setting(containerEl)
            .setName('Download audio')
            .setDesc('Store and download the audio associated with the transcript')
            .addToggle((toggle) => { var _a; return toggle.setValue((_a = this.getSetting('downloadAudio')) !== null && _a !== void 0 ? _a : false).onChange(this.createToggleHandler('downloadAudio')); });
        new obsidian.Setting(containerEl)
            .setName('Date Format')
            .setDesc('Format of the date used in the templates below (moment.js format)')
            .addText((text) => {
            var _a;
            return text
                .setPlaceholder('YYYY-MM-DD')
                .setValue((_a = this.getSetting('dateFormat')) !== null && _a !== void 0 ? _a : '')
                .onChange(this.createTextInputHandler('dateFormat'));
        });
        new obsidian.Setting(containerEl)
            .setName('Filename Date Format')
            .setDesc('Format of the date used to replace {{date}} if in Filename Template below (moment.js format)')
            .addText((text) => {
            var _a;
            return text
                .setPlaceholder('YYYY-MM-DD')
                .setValue((_a = this.getSetting('filenameDateFormat')) !== null && _a !== void 0 ? _a : '')
                .onChange(this.createTextInputHandler('filenameDateFormat'));
        });
        new obsidian.Setting(containerEl)
            .setName('Filename Template')
            .setDesc('Template for the filename of synced notes. Available variables: {{date}}, {{title}}')
            .addText((text) => {
            var _a;
            return text
                .setPlaceholder('{{date}} {{title}}')
                .setValue((_a = this.getSetting('filenameTemplate')) !== null && _a !== void 0 ? _a : '')
                .onChange(this.createTextInputHandler('filenameTemplate'));
        });
    }
    async renderTemplateSettings(containerEl) {
        new obsidian.Setting(containerEl).setName('Notes Formatting').setHeading();
        new obsidian.Setting(containerEl)
            .setName('Frontmatter Template')
            .setDesc('Frontmatter / properties template for notes. recording_id and the three dashes before and after properties automatically added')
            .addTextArea((text) => this.createTextAreaWithAutoresize(text, 'frontmatterTemplate', containerEl));
        new obsidian.Setting(containerEl)
            .setName('Note Template')
            .setDesc('Template for synced notes. Available variables: {{recording_id}}, {{title}}, {{date}}, {{duration}}, {{created_at}}, {{updated_at}}, {{tags}}, {{transcript}}, {{embedded_audio_link}}, {{audio_filename}}, {{summary}}, {{tidy}}, {{points}}, {{todo}}, {{email}}, {{tweet}}, {{blog}}, {{custom}}, {{meeting_report}}, {{my_notes}}, {{parent_note}} and {{related_notes}}')
            .addTextArea((text) => this.createTextAreaWithAutoresize(text, 'noteTemplate', containerEl));
    }
    async renderAdvancedSettings(containerEl) {
        new obsidian.Setting(containerEl)
            .setName('Use custom frontmatter property for date sorting')
            .setDesc('If you have changed the frontmatter template above, you can specify here which property should be used, e.g. to include todays notes.')
            .addToggle((toggle) => {
            var _a;
            return toggle.setValue((_a = this.getSetting('useCustomChangedAtProperty')) !== null && _a !== void 0 ? _a : false).onChange(this.createToggleHandler('useCustomChangedAtProperty', async () => {
                await this.display();
            }));
        })
            .addText((text) => {
            var _a;
            text
                .setPlaceholder('Custom setting value')
                .setValue((_a = this.getSetting('customChangedAtProperty')) !== null && _a !== void 0 ? _a : '')
                .setDisabled(!this.getSetting('useCustomChangedAtProperty'))
                .onChange(this.createTextInputHandler('customChangedAtProperty'));
            return text;
        });
    }
    createTextInputHandler(settingKey) {
        return async (value) => {
            await this.setSetting(settingKey, value);
        };
    }
    createToggleHandler(settingKey, afterChange) {
        return async (value) => {
            await this.setSetting(settingKey, value);
            if (afterChange) {
                await afterChange();
            }
        };
    }
    /**
     * Creates a textarea with autoresize functionality
     */
    createTextAreaWithAutoresize(text, settingKey, containerEl) {
        var _a;
        const current = String((_a = this.getSetting(settingKey)) !== null && _a !== void 0 ? _a : '');
        text.setPlaceholder(current).setValue(current).onChange(this.createTextInputHandler(settingKey));
        text.inputEl.classList.add('autoresize');
        AppHelper.autoResizeTextArea(text.inputEl);
        text.inputEl.addEventListener('input', () => AppHelper.autoResizeTextArea(text.inputEl));
        containerEl.appendChild(text.inputEl);
        return text;
    }
    async handleLogin() {
        const token = this.getSetting('token');
        if (!token) {
            new obsidian.Notice('Please provide a token first.');
            return;
        }
        this.vnApi.setToken(token);
        const response = await this.vnApi.getUserInfo();
        if (response) {
            // Cache user info on successful login
            await this.setSetting('cachedUserInfo', response);
            await this.plugin.saveSettings();
            await this.display();
            this.plugin.setupAutoSync();
            new obsidian.Notice('Logged in successfully');
        }
        else {
            new obsidian.Notice('Failed to log in with provided token. Please check and try again.');
        }
    }
    async handleLogout() {
        new obsidian.Notice('Successfully logged out.');
        this.plugin.clearAutoSync();
        await this.setSetting('token', null);
        await this.setSetting('lastSyncedNoteUpdatedAt', null);
        await this.setSetting('cachedUserInfo', null);
        await this.setSetting('deletedLocalRecordingIds', []);
        await this.display();
    }
    async handleSync() {
        this.plugin.syncedRecording = [];
        await this.toggleSyncingState(true);
        await this.plugin.sync();
        // ensure UI toggled off after sync completes
        await this.toggleSyncingState(false);
    }
    async toggleSyncingState(isSyncing = false) {
        const label = this.containerEl.querySelector('.sync-btn-label');
        if (label) {
            label.textContent = isSyncing ? 'Syncing' : 'Sync Now';
        }
        const syncDotsEl = this.containerEl.querySelector('.sync-dots');
        if (syncDotsEl) {
            syncDotsEl.style.display = isSyncing ? 'inline-flex' : 'none';
        }
    }
    getSetting(key) {
        return this.plugin.settings[key];
    }
    async setSetting(key, value) {
        this.plugin.settings[key] = value;
        await this.plugin.saveSettings();
    }
}

var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};

function commonjsRequire(path) {
	throw new Error('Could not dynamically require "' + path + '". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.');
}

var jinja$1 = {exports: {}};

/*!
 * Jinja Templating for JavaScript v0.1.8
 * https://github.com/sstur/jinja-js
 *
 * This is a slimmed-down Jinja2 implementation [http://jinja.pocoo.org/]
 *
 * In the interest of simplicity, it deviates from Jinja2 as follows:
 * - Line statements, cycle, super, macros and block nesting are not implemented
 * - auto escapes html by default (the filter is "html" not "e")
 * - Only "html" and "safe" filters are built in
 * - Filters are not valid in expressions; `foo|length > 1` is not valid
 * - Expression Tests (`if num is odd`) not implemented (`is` translates to `==` and `isnot` to `!=`)
 *
 * Notes:
 * - if property is not found, but method '_get' exists, it will be called with the property name (and cached)
 * - `{% for n in obj %}` iterates the object's keys; get the value with `{% for n in obj %}{{ obj[n] }}{% endfor %}`
 * - subscript notation `a[0]` takes literals or simple variables but not `a[item.key]`
 * - `.2` is not a valid number literal; use `0.2`
 *
 */

(function (module, exports) {
	(function(definition) {
	  {
	    // CommonJS/Node
	    return definition(commonjsRequire, exports, module);
	  }
	})(function(require, jinja) {
	  var STRINGS = /'(\\.|[^'])*'|"(\\.|[^"'"])*"/g;
	  var IDENTS_AND_NUMS = /([$_a-z][$\w]*)|([+-]?\d+(\.\d+)?)/g;
	  var NUMBER = /^[+-]?\d+(\.\d+)?$/;
	  //non-primitive literals (array and object literals)
	  var NON_PRIMITIVES = /\[[@#~](,[@#~])*\]|\[\]|\{([@i]:[@#~])(,[@i]:[@#~])*\}|\{\}/g;
	  //bare identifiers such as variables and in object literals: {foo: 'value'}
	  var IDENTIFIERS = /[$_a-z][$\w]*/ig;
	  var VARIABLES = /i(\.i|\[[@#i]\])*/g;
	  var ACCESSOR = /(\.i|\[[@#i]\])/g;
	  var OPERATORS = /(===?|!==?|>=?|<=?|&&|\|\||[+\-\*\/%])/g;
	  //extended (english) operators
	  var EOPS = /(^|[^$\w])(and|or|not|is|isnot)([^$\w]|$)/g;
	  var LEADING_SPACE = /^\s+/;
	  var TRAILING_SPACE = /\s+$/;

	  var START_TOKEN = /\{\{\{|\{\{|\{%|\{#/;
	  var TAGS = {
	    '{{{': /^('(\\.|[^'])*'|"(\\.|[^"'"])*"|.)+?\}\}\}/,
	    '{{': /^('(\\.|[^'])*'|"(\\.|[^"'"])*"|.)+?\}\}/,
	    '{%': /^('(\\.|[^'])*'|"(\\.|[^"'"])*"|.)+?%\}/,
	    '{#': /^('(\\.|[^'])*'|"(\\.|[^"'"])*"|.)+?#\}/
	  };

	  var delimeters = {
	    '{%': 'directive',
	    '{{': 'output',
	    '{#': 'comment'
	  };

	  var operators = {
	    and: '&&',
	    or: '||',
	    not: '!',
	    is: '==',
	    isnot: '!='
	  };

	  var constants = {
	    'true': true,
	    'false': false,
	    'null': null
	  };

	  function Parser() {
	    this.nest = [];
	    this.compiled = [];
	    this.childBlocks = 0;
	    this.parentBlocks = 0;
	    this.isSilent = false;
	  }

	  Parser.prototype.push = function(line) {
	    if (!this.isSilent) {
	      this.compiled.push(line);
	    }
	  };

	  Parser.prototype.parse = function(src) {
	    this.tokenize(src);
	    return this.compiled;
	  };

	  Parser.prototype.tokenize = function(src) {
	    var lastEnd = 0, parser = this, trimLeading = false;
	    matchAll(src, START_TOKEN, function(open, index, src) {
	      //here we match the rest of the src against a regex for this tag
	      var match = src.slice(index + open.length).match(TAGS[open]);
	      match = (match ? match[0] : '');
	      //here we sub out strings so we don't get false matches
	      var simplified = match.replace(STRINGS, '@');
	      //if we don't have a close tag or there is a nested open tag
	      if (!match || ~simplified.indexOf(open)) {
	        return index + 1;
	      }
	      var inner = match.slice(0, 0 - open.length);
	      //check for white-space collapse syntax
	      if (inner.charAt(0) == '-') var wsCollapseLeft = true;
	      if (inner.slice(-1) == '-') var wsCollapseRight = true;
	      inner = inner.replace(/^-|-$/g, '').trim();
	      //if we're in raw mode and we are not looking at an "endraw" tag, move along
	      if (parser.rawMode && (open + inner) != '{%endraw') {
	        return index + 1;
	      }
	      var text = src.slice(lastEnd, index);
	      lastEnd = index + open.length + match.length;
	      if (trimLeading) text = trimLeft(text);
	      if (wsCollapseLeft) text = trimRight(text);
	      if (wsCollapseRight) trimLeading = true;
	      if (open == '{{{') {
	        //liquid-style: make {{{x}}} => {{x|safe}}
	        open = '{{';
	        inner += '|safe';
	      }
	      parser.textHandler(text);
	      parser.tokenHandler(open, inner);
	    });
	    var text = src.slice(lastEnd);
	    if (trimLeading) text = trimLeft(text);
	    this.textHandler(text);
	  };

	  Parser.prototype.textHandler = function(text) {
	    this.push('write(' + JSON.stringify(text) + ');');
	  };

	  Parser.prototype.tokenHandler = function(open, inner) {
	    var type = delimeters[open];
	    if (type == 'directive') {
	      this.compileTag(inner);
	    } else
	    if (type == 'output') {
	      var extracted = this.extractEnt(inner, STRINGS, '@');
	      //replace || operators with ~
	      extracted.src = extracted.src.replace(/\|\|/g, '~').split('|');
	      //put back || operators
	      extracted.src = extracted.src.map(function(part) {
	        return part.split('~').join('||');
	      });
	      var parts = this.injectEnt(extracted, '@');
	      if (parts.length > 1) {
	        var filters = parts.slice(1).map(this.parseFilter.bind(this));
	        this.push('filter(' + this.parseExpr(parts[0]) + ',' + filters.join(',') + ');');
	      } else {
	        this.push('filter(' + this.parseExpr(parts[0]) + ');');
	      }
	    }
	  };

	  Parser.prototype.compileTag = function(str) {
	    var directive = str.split(' ')[0];
	    var handler = tagHandlers[directive];
	    if (!handler) {
	      throw new Error('Invalid tag: ' + str);
	    }
	    handler.call(this, str.slice(directive.length).trim());
	  };

	  Parser.prototype.parseFilter = function(src) {
	    src = src.trim();
	    var match = src.match(/[:(]/);
	    var i = match ? match.index : -1;
	    if (i < 0) return JSON.stringify([src]);
	    var name = src.slice(0, i);
	    var args = src.charAt(i) == ':' ? src.slice(i + 1) : src.slice(i + 1, -1);
	    args = this.parseExpr(args, {terms: true});
	    return '[' + JSON.stringify(name) + ',' + args + ']';
	  };

	  Parser.prototype.extractEnt = function(src, regex, placeholder) {
	    var subs = [], isFunc = typeof placeholder == 'function';
	    src = src.replace(regex, function(str) {
	      var replacement = isFunc ? placeholder(str) : placeholder;
	      if (replacement) {
	        subs.push(str);
	        return replacement;
	      }
	      return str;
	    });
	    return {src: src, subs: subs};
	  };

	  Parser.prototype.injectEnt = function(extracted, placeholder) {
	    var src = extracted.src, subs = extracted.subs, isArr = Array.isArray(src);
	    var arr = (isArr) ? src : [src];
	    var re = new RegExp('[' + placeholder + ']', 'g'), i = 0;
	    arr.forEach(function(src, index) {
	      arr[index] = src.replace(re, function() {
	        return subs[i++];
	      });
	    });
	    return isArr ? arr : arr[0];
	  };

	  //replace complex literals without mistaking subscript notation with array literals
	  Parser.prototype.replaceComplex = function(s) {
	    var parsed = this.extractEnt(s, /i(\.i|\[[@#i]\])+/g, 'v');
	    parsed.src = parsed.src.replace(NON_PRIMITIVES, '~');
	    return this.injectEnt(parsed, 'v');
	  };

	  //parse expression containing literals (including objects/arrays) and variables (including dot and subscript notation)
	  //valid expressions: `a + 1 > b.c or c == null`, `a and b[1] != c`, `(a < b) or (c < d and e)`, 'a || [1]`
	  Parser.prototype.parseExpr = function(src, opts) {
	    opts = opts || {};
	    //extract string literals -> @
	    var parsed1 = this.extractEnt(src, STRINGS, '@');
	    //note: this will catch {not: 1} and a.is; could we replace temporarily and then check adjacent chars?
	    parsed1.src = parsed1.src.replace(EOPS, function(s, before, op, after) {
	      return (op in operators) ? before + operators[op] + after : s;
	    });
	    //sub out non-string literals (numbers/true/false/null) -> #
	    // the distinction is necessary because @ can be object identifiers, # cannot
	    var parsed2 = this.extractEnt(parsed1.src, IDENTS_AND_NUMS, function(s) {
	      return (s in constants || NUMBER.test(s)) ? '#' : null;
	    });
	    //sub out object/variable identifiers -> i
	    var parsed3 = this.extractEnt(parsed2.src, IDENTIFIERS, 'i');
	    //remove white-space
	    parsed3.src = parsed3.src.replace(/\s+/g, '');

	    //the rest of this is simply to boil the expression down and check validity
	    var simplified = parsed3.src;
	    //sub out complex literals (objects/arrays) -> ~
	    // the distinction is necessary because @ and # can be subscripts but ~ cannot
	    while (simplified != (simplified = this.replaceComplex(simplified)));
	    //now @ represents strings, # represents other primitives and ~ represents non-primitives
	    //replace complex variables (those with dot/subscript accessors) -> v
	    while (simplified != (simplified = simplified.replace(/i(\.i|\[[@#i]\])+/, 'v')));
	    //empty subscript or complex variables in subscript, are not permitted
	    simplified = simplified.replace(/[iv]\[v?\]/g, 'x');
	    //sub in "i" for @ and # and ~ and v (now "i" represents all literals, variables and identifiers)
	    simplified = simplified.replace(/[@#~v]/g, 'i');
	    //sub out operators
	    simplified = simplified.replace(OPERATORS, '%');
	    //allow 'not' unary operator
	    simplified = simplified.replace(/!+[i]/g, 'i');
	    var terms = opts.terms ? simplified.split(',') : [simplified];
	    terms.forEach(function(term) {
	      //simplify logical grouping
	      while (term != (term = term.replace(/\(i(%i)*\)/g, 'i')));
	      if (!term.match(/^i(%i)*$/)) {
	        throw new Error('Invalid expression: ' + src);
	      }
	    });
	    parsed3.src = parsed3.src.replace(VARIABLES, this.parseVar.bind(this));
	    parsed2.src = this.injectEnt(parsed3, 'i');
	    parsed1.src = this.injectEnt(parsed2, '#');
	    return this.injectEnt(parsed1, '@');
	  };

	  Parser.prototype.parseVar = function(src) {
	    var args = Array.prototype.slice.call(arguments);
	    var str = args.pop(), index = args.pop();
	    //quote bare object identifiers (might be a reserved word like {while: 1})
	    if (src == 'i' && str.charAt(index + 1) == ':') {
	      return '"i"';
	    }
	    var parts = ['"i"'];
	    src.replace(ACCESSOR, function(part) {
	      if (part == '.i') {
	        parts.push('"i"');
	      } else
	      if (part == '[i]') {
	        parts.push('get("i")');
	      } else {
	        parts.push(part.slice(1, -1));
	      }
	    });
	    return 'get(' + parts.join(',') + ')';
	  };

	  //escapes a name to be used as a javascript identifier
	  Parser.prototype.escName = function(str) {
	    return str.replace(/\W/g, function(s) {
	      return '$' + s.charCodeAt(0).toString(16);
	    });
	  };

	  Parser.prototype.parseQuoted = function(str) {
	    if (str.charAt(0) == "'") {
	      str = str.slice(1, -1).replace(/\\.|"/, function(s) {
	        if (s == "\\'") return "'";
	        return s.charAt(0) == '\\' ? s : ('\\' + s);
	      });
	      str = '"' + str + '"';
	    }
	    //todo: try/catch or deal with invalid characters (linebreaks, control characters)
	    return JSON.parse(str);
	  };


	  //the context 'this' inside tagHandlers is the parser instance
	  var tagHandlers = {
	    'if': function(expr) {
	      this.push('if (' + this.parseExpr(expr) + ') {');
	      this.nest.unshift('if');
	    },
	    'else': function() {
	      if (this.nest[0] == 'for') {
	        this.push('}, function() {');
	      } else {
	        this.push('} else {');
	      }
	    },
	    'elseif': function(expr) {
	      this.push('} else if (' + this.parseExpr(expr) + ') {');
	    },
	    'endif': function() {
	      this.nest.shift();
	      this.push('}');
	    },
	    'for': function(str) {
	      var i = str.indexOf(' in ');
	      var name = str.slice(0, i).trim();
	      var expr = str.slice(i + 4).trim();
	      this.push('each(' + this.parseExpr(expr) + ',' + JSON.stringify(name) + ',function() {');
	      this.nest.unshift('for');
	    },
	    'endfor': function() {
	      this.nest.shift();
	      this.push('});');
	    },
	    'raw': function() {
	      this.rawMode = true;
	    },
	    'endraw': function() {
	      this.rawMode = false;
	    },
	    'set': function(stmt) {
	      var i = stmt.indexOf('=');
	      var name = stmt.slice(0, i).trim();
	      var expr = stmt.slice(i + 1).trim();
	      this.push('set(' + JSON.stringify(name) + ',' + this.parseExpr(expr) + ');');
	    },
	    'block': function(name) {
	      if (this.isParent) {
	        ++this.parentBlocks;
	        var blockName = 'block_' + (this.escName(name) || this.parentBlocks);
	        this.push('block(typeof ' + blockName + ' == "function" ? ' + blockName + ' : function() {');
	      } else
	      if (this.hasParent) {
	        this.isSilent = false;
	        ++this.childBlocks;
	        blockName = 'block_' + (this.escName(name) || this.childBlocks);
	        this.push('function ' + blockName + '() {');
	      }
	      this.nest.unshift('block');
	    },
	    'endblock': function() {
	      this.nest.shift();
	      if (this.isParent) {
	        this.push('});');
	      } else
	      if (this.hasParent) {
	        this.push('}');
	        this.isSilent = true;
	      }
	    },
	    'extends': function(name) {
	      name = this.parseQuoted(name);
	      var parentSrc = this.readTemplateFile(name);
	      this.isParent = true;
	      this.tokenize(parentSrc);
	      this.isParent = false;
	      this.hasParent = true;
	      //silence output until we enter a child block
	      this.isSilent = true;
	    },
	    'include': function(name) {
	      name = this.parseQuoted(name);
	      var incSrc = this.readTemplateFile(name);
	      this.isInclude = true;
	      this.tokenize(incSrc);
	      this.isInclude = false;
	    }
	  };

	  //liquid style
	  tagHandlers.assign = tagHandlers.set;
	  //python/django style
	  tagHandlers.elif = tagHandlers.elseif;

	  var getRuntime = function runtime(data, opts) {
	    var defaults = {autoEscape: 'html'};
	    var _toString = Object.prototype.toString;
	    var _hasOwnProperty = Object.prototype.hasOwnProperty;
	    var toString = function(val) {
	      if (val == null) return '';
	      return (typeof val.toString == 'function') ? val.toString() : _toString.call(val);
	    };
	    var extend = function(dest, src) {
	      Object.keys(src).forEach(function(key) {
	        dest[key] = src[key];
	      });
	      return dest;
	    };
	    //get a value, lexically, starting in current context; a.b -> get("a","b")
	    var get = function() {
	      var val, n = arguments[0], c = stack.length;
	      while (c--) {
	        val = stack[c][n];
	        if (typeof val != 'undefined') break;
	      }
	      for (var i = 1, len = arguments.length; i < len; i++) {
	        if (val == null) continue;
	        n = arguments[i];
	        val = (_hasOwnProperty.call(val, n)) ? val[n] : (typeof val._get == 'function' ? (val[n] = val._get(n)) : null);
	      }
	      return (val == null) ? null : val;
	    };
	    var set = function(n, val) {
	      stack[stack.length - 1][n] = val;
	    };
	    var push = function(ctx) {
	      stack.push(ctx || {});
	    };
	    var pop = function() {
	      stack.pop();
	    };
	    var write = function(str) {
	      output.push(str);
	    };
	    var filter = function(val) {
	      for (var i = 1, len = arguments.length; i < len; i++) {
	        var arr = arguments[i], name = arr[0], filter = filters[name];
	        if (filter) {
	          arr[0] = val;
	          //now arr looks like [val, arg1, arg2]
	          val = filter.apply(data, arr);
	        } else {
	          throw new Error('Invalid filter: ' + name);
	        }
	      }
	      if (opts.autoEscape && name != opts.autoEscape && name != 'safe') {
	        //auto escape if not explicitly safe or already escaped
	        val = filters[opts.autoEscape].call(data, val);
	      }
	      output.push(val);
	    };
	    var each = function(obj, loopvar, fn1, fn2) {
	      if (obj == null) return;
	      var arr = Array.isArray(obj) ? obj : Object.keys(obj), len = arr.length;
	      var ctx = {loop: {length: len, first: arr[0], last: arr[len - 1]}};
	      push(ctx);
	      for (var i = 0; i < len; i++) {
	        extend(ctx.loop, {index: i + 1, index0: i});
	        fn1(ctx[loopvar] = arr[i]);
	      }
	      if (len == 0 && fn2) fn2();
	      pop();
	    };
	    var block = function(fn) {
	      push();
	      fn();
	      pop();
	    };
	    var render = function() {
	      return output.join('');
	    };
	    data = data || {};
	    opts = extend(defaults, opts || {});
	    var filters = extend({
	      html: function(val) {
	        return toString(val)
	          .split('&').join('&amp;')
	          .split('<').join('&lt;')
	          .split('>').join('&gt;')
	          .split('"').join('&quot;');
	      },
	      safe: function(val) {
	        return val;
	      }
	    }, opts.filters || {});
	    var stack = [Object.create(data || {})], output = [];
	    return {get: get, set: set, push: push, pop: pop, write: write, filter: filter, each: each, block: block, render: render};
	  };

	  var runtime;

	  jinja.compile = function(markup, opts) {
	    opts = opts || {};
	    var parser = new Parser();
	    parser.readTemplateFile = this.readTemplateFile;
	    var code = [];
	    code.push('function render($) {');
	    code.push('var get = $.get, set = $.set, push = $.push, pop = $.pop, write = $.write, filter = $.filter, each = $.each, block = $.block;');
	    code.push.apply(code, parser.parse(markup));
	    code.push('return $.render();');
	    code.push('}');
	    code = code.join('\n');
	    if (opts.runtime === false) {
	      var fn = new Function('data', 'options', 'return (' + code + ')(runtime(data, options))');
	    } else {
	      runtime = runtime || (runtime = getRuntime.toString());
	      fn = new Function('data', 'options', 'return (' + code + ')((' + runtime + ')(data, options))');
	    }
	    return {render: fn};
	  };

	  jinja.render = function(markup, data, opts) {
	    var tmpl = jinja.compile(markup);
	    return tmpl.render(data, opts);
	  };

	  jinja.templateFiles = [];

	  jinja.readTemplateFile = function(name) {
	    var templateFiles = this.templateFiles || [];
	    var templateFile = templateFiles[name];
	    if (templateFile == null) {
	      throw new Error('Template file not found: ' + name);
	    }
	    return templateFile;
	  };


	  /*!
	   * Helpers
	   */

	  function trimLeft(str) {
	    return str.replace(LEADING_SPACE, '');
	  }

	  function trimRight(str) {
	    return str.replace(TRAILING_SPACE, '');
	  }

	  function matchAll(str, reg, fn) {
	    //copy as global
	    reg = new RegExp(reg.source, 'g' + (reg.ignoreCase ? 'i' : '') + (reg.multiline ? 'm' : ''));
	    var match;
	    while ((match = reg.exec(str))) {
	      var result = fn(match[0], match.index, str);
	      if (typeof result == 'number') {
	        reg.lastIndex = result;
	      }
	    }
	  }

	}); 
} (jinja$1, jinja$1.exports));

var jinjaExports = jinja$1.exports;

var jinja = jinjaExports;

class AppConfig {
    static get DEFAULT_SETTINGS() {
        return {
            automaticSync: true,
            syncTimeout: 180,
            downloadAudio: false,
            syncDirectory: 'voicenotes',
            deleteSynced: false,
            reallyDeleteSynced: false,
            todoTag: '',
            filenameDateFormat: 'YYYY-MM-DD',
            frontmatterTemplate: `duration: {{duration}}
created_at: {{created_at}}
updated_at: {{updated_at}}
{{tags}}`,
            noteTemplate: `# {{ title }}

Date: {{ date }}

{% if my_notes %}
## My notes

{{ my_notes }}
{% endif %}

{% if meeting_report %}
## Meeting Report

{{ meeting_report }}
{% endif %}

{% if summary %}
## Summary

{{ summary }}
{% endif %}

{% if points %}
## Main points

{{ points }}
{% endif %}

{% if attachments %}
## Attachments

{{ attachments }}
{% endif %}

{% if tidy %}
## Tidy Transcript

{{ tidy }}

{% else %}
## Transcript

{{ transcript }}
{% endif %}

{% if embedded_audio_link %}
{{ embedded_audio_link }}
{% endif %}

{% if audio_filename %}
[[{{ audio_filename }}|Audio]]
{% endif %}

{% if todo %}
## Todos

{{ todo }}
{% endif %}

{% if email %}
## Email

{{ email }}
{% endif %}

{% if blog %}
## Blog

{{ blog }}
{% endif %}

{% if tweet %}
## Tweet

{{ tweet }}
{% endif %}

{% if custom %}
## Others

{{ custom }}
{% endif %}

{% if tags %}
## Tags

{{ tags }}
{% endif %}

{% if related_notes %}
# Related notes

{{ related_notes }}
{% endif %}

{% if parent_note %}
## Parent note

- {{ parent_note }}
{% endif %}

{% if subnotes %}
## Subnotes

{{ subnotes }}
{% endif %}`,
            filenameTemplate: `{{date}} {{title}}`,
            excludeTags: [],
            tagFilterMode: 'exclude',
            dateFormat: 'YYYY-MM-DD',
            useCustomChangedAtProperty: false,
            customChangedAtProperty: 'created_at',
            deletedLocalRecordingIds: [],
        };
    }
}

function registerManualSyncCommand(plugin) {
    plugin.addCommand({
        id: 'manual-sync-voicenotes',
        name: 'Manual Sync Voicenotes',
        callback: async () => await plugin.sync(),
    });
}

function registerInsertTodayNotesCommand(plugin) {
    plugin.addCommand({
        id: 'insert-voicenotes-from-today',
        name: "Insert Today's Voicenotes",
        editorCallback: async (editor) => {
            if (!plugin.settings.token) {
                new obsidian.Notice('No access available, please login in plugin settings');
                return;
            }
            const todaysRecordings = await getTodaysSyncedRecordings();
            if (todaysRecordings.length === 0) {
                new obsidian.Notice('No recordings from today found');
                return;
            }
            const listOfToday = todaysRecordings.map((filename) => `- [[${filename}]]`).join('\n');
            editor.replaceSelection(listOfToday);
        },
    });
    const getTodaysSyncedRecordings = async () => {
        const { vault } = plugin.app;
        const markdownFiles = vault
            .getMarkdownFiles()
            .filter((file) => file.path.startsWith(plugin.settings.syncDirectory));
        return (await Promise.all(markdownFiles.map(async (file) => ((await isRecordingFromToday(file)) ? file.basename : undefined)))).filter((filename) => filename !== undefined);
    };
    const isRecordingFromToday = async (file) => {
        var _a, _b;
        return DateTimeHelper.isToday(await ((_b = (_a = plugin.app.metadataCache.getFileCache(file)) === null || _a === void 0 ? void 0 : _a.frontmatter) === null || _b === void 0 ? void 0 : _b[plugin.settings.useCustomChangedAtProperty ? plugin.settings.customChangedAtProperty : 'created_at']));
    };
}

function registerDeleteRemoteNoteCommand(plugin) {
    plugin.addCommand({
        id: 'delete-remote-voicenote',
        name: 'Delete Remote Voicenote',
        callback: async () => {
            if (!plugin.settings.token) {
                new obsidian.Notice('No access available, please login in plugin settings');
                return;
            }
            const activeFile = plugin.app.workspace.getActiveFile();
            if (activeFile) {
                const cache = plugin.app.metadataCache.getFileCache(activeFile);
                if (cache && cache.frontmatter) {
                    const frontmatter = cache.frontmatter;
                    const confirmDelete = confirm(`Are you sure you want to delete this note from Voicenotes?`);
                    if (confirmDelete) {
                        try {
                            await plugin.vnApi.deleteRecording(frontmatter.recording_id);
                            // Successfully deleted, now remove recording_id from frontmatter using Obsidian API
                            await plugin.app.fileManager.processFrontMatter(activeFile, (fm) => {
                                delete fm.recording_id;
                            });
                            new obsidian.Notice('Recording deleted successfully and recording_id removed from note');
                        }
                        catch (error) {
                            new obsidian.Notice('Failed to delete recording from remote');
                            console.error('Error deleting recording:', error);
                        }
                    }
                }
            }
        },
    });
}

function registerCommands(plugin) {
    registerManualSyncCommand(plugin);
    registerInsertTodayNotesCommand(plugin);
    registerDeleteRemoteNoteCommand(plugin);
}

var AttachmentType;
(function (AttachmentType) {
    AttachmentType[AttachmentType["LINK"] = 1] = "LINK";
    AttachmentType[AttachmentType["IMAGE"] = 2] = "IMAGE";
    AttachmentType[AttachmentType["TEXT"] = 3] = "TEXT";
})(AttachmentType || (AttachmentType = {}));

var build = {};

function isHighSurrogate$1(codePoint) {
  return codePoint >= 0xd800 && codePoint <= 0xdbff;
}

function isLowSurrogate$1(codePoint) {
  return codePoint >= 0xdc00 && codePoint <= 0xdfff;
}

// Truncate string by size in bytes
var truncate$1 = function truncate(getLength, string, byteLength) {
  if (typeof string !== "string") {
    throw new Error("Input must be string");
  }

  var charLength = string.length;
  var curByteLength = 0;
  var codePoint;
  var segment;

  for (var i = 0; i < charLength; i += 1) {
    codePoint = string.charCodeAt(i);
    segment = string[i];

    if (isHighSurrogate$1(codePoint) && isLowSurrogate$1(string.charCodeAt(i + 1))) {
      i += 1;
      segment += string[i];
    }

    curByteLength += getLength(segment);

    if (curByteLength === byteLength) {
      return string.slice(0, i + 1);
    }
    else if (curByteLength > byteLength) {
      return string.slice(0, i - segment.length + 1);
    }
  }

  return string;
};

function isHighSurrogate(codePoint) {
  return codePoint >= 0xd800 && codePoint <= 0xdbff;
}

function isLowSurrogate(codePoint) {
  return codePoint >= 0xdc00 && codePoint <= 0xdfff;
}

// Truncate string by size in bytes
var browser$1 = function getByteLength(string) {
  if (typeof string !== "string") {
    throw new Error("Input must be string");
  }

  var charLength = string.length;
  var byteLength = 0;
  var codePoint = null;
  var prevCodePoint = null;
  for (var i = 0; i < charLength; i++) {
    codePoint = string.charCodeAt(i);
    // handle 4-byte non-BMP chars
    // low surrogate
    if (isLowSurrogate(codePoint)) {
      // when parsing previous hi-surrogate, 3 is added to byteLength
      if (prevCodePoint != null && isHighSurrogate(prevCodePoint)) {
        byteLength += 1;
      }
      else {
        byteLength += 3;
      }
    }
    else if (codePoint <= 0x7f ) {
      byteLength += 1;
    }
    else if (codePoint >= 0x80 && codePoint <= 0x7ff) {
      byteLength += 2;
    }
    else if (codePoint >= 0x800 && codePoint <= 0xffff) {
      byteLength += 3;
    }
    prevCodePoint = codePoint;
  }

  return byteLength;
};

var truncate = truncate$1;
var getLength = browser$1;
var browser = truncate.bind(null, getLength);

var __importDefault = (commonjsGlobal && commonjsGlobal.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(build, "__esModule", { value: true });
const truncate_utf8_bytes_1 = __importDefault(browser);
/**
 * Replaces characters in strings that are illegal/unsafe for filenames.
 * Unsafe characters are either removed or replaced by a substitute set
 * in the optional `options` object.
 *
 * Illegal Characters on Various Operating Systems
 * / ? < > \ : * | "
 * https://kb.acronis.com/content/39790
 *
 * Unicode Control codes
 * C0 0x00-0x1f & C1 (0x80-0x9f)
 * http://en.wikipedia.org/wiki/C0_and_C1_control_codes
 *
 * Reserved filenames on Unix-based systems (".", "..")
 * Reserved filenames in Windows ("CON", "PRN", "AUX", "NUL", "COM1",
 * "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
 * "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", and
 * "LPT9") case-insesitively and with or without filename extensions.
 *
 * Capped at 255 characters in length.
 * http://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs
 *
 * @param  {String} input   Original filename
 * @param  {Object} options {replacement: String}
 * @return {String}         Sanitized filename
 */
const illegalRe = /[\/\?<>\\:\*\|":]/g;
/* tslint:disable-next-line:no-control-regex */
const controlRe = /[\x00-\x1f\x80-\x9f]/g;
const reservedRe = /^\.+$/;
const windowsReservedRe = /^(con|prn|aux|nul|com[0-9]|lpt[0-9])(\..*)?$/i;
const windowsTrailingRe = /[\. ]+$/;
function replace(input, replacement) {
    const sanitized = input
        .replace(illegalRe, replacement)
        .replace(controlRe, replacement)
        .replace(reservedRe, replacement)
        .replace(windowsReservedRe, replacement)
        .replace(windowsTrailingRe, replacement);
    return truncate_utf8_bytes_1.default(sanitized, 255);
}
function sanitize(input, options) {
    const replacement = (options && options.replacement) || "";
    const output = replace(input, replacement);
    if (replacement === "") {
        return output;
    }
    return replace(output, "");
}
var sanitize_1 = build.sanitize = sanitize;

class RecordingUtility {
    constructor(plugin) {
        this.plugin = plugin;
    }
    static getLatestNote(recordings) {
        return recordings.reduce((latest, current) => {
            return new Date(current.updated_at) > new Date(latest.updated_at) ? current : latest;
        });
    }
    sanitizedTitle(title, created_at) {
        const date = DateTimeHelper.formatDate(created_at, this.plugin.settings.filenameDateFormat);
        const generatedTitle = this.plugin.settings.filenameTemplate.replace('{{date}}', date).replace('{{title}}', title);
        return sanitize_1(generatedTitle).trim();
    }
}

class VoiceNotesPlugin extends obsidian.Plugin {
    constructor(app, manifest) {
        super(app, manifest);
        this.syncedRecording = [];
        this.syncIntervalId = null;
        this.fs = app.vault.adapter;
        this.recordingUtility = new RecordingUtility(this);
    }
    async onload() {
        await this.loadSettings();
        this.addSettingTab(new VoiceNotesSettingTab(this.app, this));
        if (this.settings.token) {
            this.setupAutoSync();
        }
        registerCommands(this);
        this.registerEvent(this.app.metadataCache.on('deleted', async (deletedFile, prevCache) => {
            var _a, _b, _c;
            if ((_a = prevCache.frontmatter) === null || _a === void 0 ? void 0 : _a.recording_id) {
                this.syncedRecording = this.syncedRecording.filter((r) => { var _a; return r.recording_id !== ((_a = prevCache.frontmatter) === null || _a === void 0 ? void 0 : _a.recording_id); });
                if (!this.settings.deletedLocalRecordingIds) {
                    this.settings.deletedLocalRecordingIds = [];
                }
                this.settings.deletedLocalRecordingIds.push((_b = prevCache.frontmatter) === null || _b === void 0 ? void 0 : _b.recording_id);
                this.settings.lastSyncedNoteUpdatedAt = this.syncedRecording.length > 0
                    ? (_c = RecordingUtility.getLatestNote(this.syncedRecording)) === null || _c === void 0 ? void 0 : _c.updated_at
                    : null;
                await this.saveSettings();
            }
        }));
        // Defer initial sync until layout is ready (faster plugin load)
        this.app.workspace.onLayoutReady(() => {
            // Only sync if we have a token and automatic sync is enabled
            if (this.settings.token && this.settings.automaticSync) {
                this.sync();
            }
        });
    }
    onunload() {
        this.syncedRecording = [];
        this.clearAutoSync();
    }
    async loadSettings() {
        this.settings = Object.assign({}, AppConfig.DEFAULT_SETTINGS, await this.loadData());
    }
    async saveSettings() {
        await this.saveData(this.settings);
        this.setupAutoSync();
    }
    setupAutoSync() {
        this.clearAutoSync();
        if (this.settings.automaticSync) {
            this.syncIntervalId = setInterval(() => {
                this.sync();
            }, this.settings.syncTimeout * 60 * 1000);
        }
    }
    clearAutoSync() {
        if (this.syncIntervalId) {
            clearInterval(this.syncIntervalId);
            this.syncIntervalId = null;
        }
    }
    /**
     * Return the recordings that we've already synced
     */
    async getSyncedRecordings() {
        const { vault } = this.app;
        const markdownFiles = vault.getMarkdownFiles().filter((file) => file.path.startsWith(this.settings.syncDirectory));
        const recordings = await Promise.all(markdownFiles.map(async (file) => {
            var _a, _b;
            const cache = this.app.metadataCache.getFileCache(file);
            const recording_id = (_a = cache === null || cache === void 0 ? void 0 : cache.frontmatter) === null || _a === void 0 ? void 0 : _a['recording_id'];
            const updated_at = (_b = cache === null || cache === void 0 ? void 0 : cache.frontmatter) === null || _b === void 0 ? void 0 : _b['updated_at'];
            if (recording_id) {
                return { recording_id, updated_at };
            }
            return null;
        }));
        return recordings.filter((r) => r !== null);
    }
    async processNote(recording, voiceNotesDir, isSubnote = false, parentTitle = '', unsyncedCount) {
        try {
            if (!recording.title) {
                new obsidian.Notice(`Unable to grab voice recording with id: ${recording.id}`);
                return;
            }
            const title = this.recordingUtility.sanitizedTitle(recording.title, recording.created_at);
            const recordingPath = obsidian.normalizePath(`${voiceNotesDir}/${title}.md`);
            // Process sub-notes, whether the note already exists or not
            if (recording.subnotes && recording.subnotes.length > 0) {
                for (const subnote of recording.subnotes) {
                    await this.processNote(subnote, voiceNotesDir, true, title, unsyncedCount);
                }
            }
            // Check if the note already exists
            const noteExists = await this.app.vault.adapter.exists(recordingPath);
            // If the note doesn't exist, or if it's a sub-note, process it
            if (!noteExists || isSubnote) {
                // Prepare data for the template
                const creationTypes = ['summary', 'points', 'tidy', 'todo', 'tweet', 'blog', 'email', 'custom', 'team-summary'];
                const creations = Object.fromEntries(creationTypes.map((type) => [
                    type,
                    recording.creations.find((creation) => creation.type === type),
                ]));
                const { transcript } = recording;
                // Destructure creations object to get individual variables if needed
                const { summary, points, tidy, todo, tweet, blog, email, custom, 'team-summary': teamSummary } = creations;
                let embeddedAudioLink = '';
                let audioFilename = '';
                // ignore for text notes
                if (this.settings.downloadAudio && recording.duration > 0) {
                    const audioPath = obsidian.normalizePath(`${voiceNotesDir}/audio`);
                    if (!(await this.app.vault.adapter.exists(audioPath))) {
                        await this.app.vault.createFolder(audioPath);
                    }
                    const outputLocationPath = obsidian.normalizePath(`${audioPath}/${recording.recording_id}.mp3`);
                    if (!(await this.app.vault.adapter.exists(outputLocationPath))) {
                        if (recording.recording_signed_url) {
                            await this.vnApi.downloadFile(this.fs, recording.recording_signed_url, outputLocationPath);
                        }
                    }
                    embeddedAudioLink = `![[${recording.recording_id}.mp3]]`;
                    audioFilename = `${recording.recording_id}.mp3`;
                }
                // Handle attachments
                let attachments = '';
                let myNotes = '';
                if (recording.attachments && recording.attachments.length > 0) {
                    const attachmentsPath = obsidian.normalizePath(`${voiceNotesDir}/attachments`);
                    if (!(await this.app.vault.adapter.exists(attachmentsPath))) {
                        await this.app.vault.createFolder(attachmentsPath);
                    }
                    const attachmentResults = await Promise.all(recording.attachments.map(async (data) => {
                        if (data.type === AttachmentType.TEXT) {
                            return { type: 'note', value: `${data.description}` };
                        }
                        else if (data.type === AttachmentType.LINK) {
                            return { type: 'attachment', value: `- ${data.description}` };
                        }
                        else if (data.type === AttachmentType.IMAGE) {
                            const filename = FileHelper.getFilenameFromUrl(data.url);
                            const attachmentPath = obsidian.normalizePath(`${attachmentsPath}/${filename}`);
                            if (!(await this.app.vault.adapter.exists(attachmentPath))) {
                                await this.vnApi.downloadFile(this.fs, data.url, attachmentPath);
                            }
                            return { type: 'attachment', value: `- ![[${filename}]]` };
                        }
                        return { type: 'attachment', value: '' };
                    }));
                    attachments = attachmentResults.filter(r => r.type === 'attachment' && r.value).map(r => r.value).join('\n');
                    myNotes = attachmentResults.filter(r => r.type === 'note' && r.value).map(r => r.value).join('\n');
                }
                // Prepare context for Jinja template
                const formattedPoints = points ? points.content.data.map((data) => `- ${data}`).join('\n') : null;
                const formattedTodos = todo
                    ? todo.content.data
                        .map((data) => `- [ ] ${data}${this.settings.todoTag ? ' #' + this.settings.todoTag : ''}`)
                        .join('\n')
                    : null;
                // Format tags, replacing spaces with hyphens for multi-word tags
                const formattedTags = recording.tags && recording.tags.length > 0
                    ? recording.tags.map((tag) => `#${tag.name.replace(/\s+/g, '-')}`).join(' ')
                    : null;
                const context = {
                    recording_id: recording.recording_id,
                    title: recording.title,
                    date: DateTimeHelper.formatDate(recording.created_at, this.settings.dateFormat),
                    duration: DateTimeHelper.formatDuration(recording.duration),
                    created_at: DateTimeHelper.formatDate(recording.created_at, this.settings.dateFormat),
                    updated_at: DateTimeHelper.formatDate(recording.updated_at, this.settings.dateFormat),
                    transcript: transcript,
                    embedded_audio_link: embeddedAudioLink,
                    audio_filename: audioFilename,
                    summary: summary ? summary.markdown_content : null,
                    tidy: tidy ? tidy.markdown_content : null,
                    points: formattedPoints,
                    todo: formattedTodos,
                    tweet: tweet ? tweet.markdown_content : null,
                    blog: blog ? blog.markdown_content : null,
                    email: email ? email.markdown_content : null,
                    custom: custom ? custom.markdown_content : null,
                    meeting_report: teamSummary ? teamSummary.markdown_content : null,
                    tags: formattedTags,
                    related_notes: recording.related_notes && recording.related_notes.length > 0
                        ? recording.related_notes
                            .map((relatedNote) => `- [[${this.recordingUtility.sanitizedTitle(relatedNote.title, relatedNote.created_at)}]]`)
                            .join('\n')
                        : null,
                    subnotes: recording.subnotes && recording.subnotes.length > 0
                        ? recording.subnotes
                            .map((subnote) => `- [[${this.recordingUtility.sanitizedTitle(subnote.title, subnote.created_at)}]]`)
                            .join('\n')
                        : null,
                    attachments: attachments,
                    my_notes: myNotes,
                    parent_note: isSubnote ? `[[${parentTitle}]]` : null,
                };
                // Render the template using Jinja
                let note = jinja.render(this.settings.noteTemplate, context).replace(/\n{3,}/g, '\n\n');
                note = FileHelper.convertHtmlToMarkdown(note);
                // Recording ID is required so we force it
                const recordingIdTemplate = `recording_id: {{recording_id}}\n`;
                const renderedFrontmatter = jinja.render(recordingIdTemplate + this.settings.frontmatterTemplate, context)
                    .replace(/\n{3,}/g, '\n\n');
                const metadata = `---\n${renderedFrontmatter}\n---\n`;
                note = metadata + note;
                // Create or update note — re-check existence since another recording
                // in the same sync batch may have created a file with the same title
                if (await this.app.vault.adapter.exists(recordingPath)) {
                    await this.app.vault.modify(this.app.vault.getFileByPath(recordingPath), note);
                }
                else {
                    await this.app.vault.create(recordingPath, note);
                }
                // Track synced recording
                const existingIndex = this.syncedRecording.findIndex((r) => r.recording_id === recording.recording_id);
                if (existingIndex !== -1) {
                    this.syncedRecording[existingIndex].updated_at = recording.updated_at;
                }
                else {
                    this.syncedRecording.push({
                        recording_id: recording.recording_id,
                        updated_at: recording.updated_at,
                    });
                }
                if (this.settings.deleteSynced && this.settings.reallyDeleteSynced) {
                    await this.vnApi.deleteRecording(recording.recording_id);
                }
            }
        }
        catch (error) {
            console.error(error);
            if (Object.prototype.hasOwnProperty.call(error, 'status')) {
                console.error(error.status);
                if (Object.prototype.hasOwnProperty.call(error, 'text')) {
                    console.error(error.text);
                }
                if (Object.prototype.hasOwnProperty.call(error, 'json')) {
                    console.error(error.json);
                }
                if (Object.prototype.hasOwnProperty.call(error, 'headers')) {
                    console.error(error.headers);
                }
                // Only clear token if it's an authentication error (401)
                if (error.status === 401) {
                    this.settings.token = undefined;
                    await this.saveSettings();
                    new obsidian.Notice(`Login token was invalid, please try logging in again.`);
                }
                else {
                    new obsidian.Notice(`Error occurred syncing some notes to this vault.`);
                }
            }
            else {
                new obsidian.Notice(`Error occurred syncing some notes to this vault.`);
            }
        }
    }
    async sync() {
        var _a, _b, _c;
        try {
            this.syncedRecording = await this.getSyncedRecordings();
            this.vnApi = new VoiceNotesApi({
                token: this.settings.token,
                lastSyncedNoteUpdatedAt: this.settings.lastSyncedNoteUpdatedAt,
                deletedLocalRecordingIds: (_a = this.settings.deletedLocalRecordingIds) !== null && _a !== void 0 ? _a : [],
                filterTags: this.settings.excludeTags,
                tagFilterMode: this.settings.tagFilterMode,
            });
            const voiceNotesDir = obsidian.normalizePath(this.settings.syncDirectory);
            if (!(await this.app.vault.adapter.exists(voiceNotesDir))) {
                new obsidian.Notice('Creating sync directory for Voice Notes Sync plugin');
                await this.app.vault.createFolder(voiceNotesDir);
            }
            const recordings = await this.vnApi.getRecordings();
            // This only happens if we aren't actually logged in, fail immediately.
            if (recordings === null) {
                this.settings.token = undefined;
                return;
            }
            const unsyncedCount = { count: 0 };
            if (recordings.links.next) {
                let nextPage = recordings.links.next;
                do {
                    await new Promise((resolve) => setTimeout(resolve, 2000));
                    const moreRecordings = await this.vnApi.getRecordingsFromLink(nextPage);
                    recordings.data.push(...moreRecordings.data);
                    nextPage = moreRecordings.links.next;
                } while (nextPage);
            }
            if (((_b = recordings === null || recordings === void 0 ? void 0 : recordings.data) === null || _b === void 0 ? void 0 : _b.length) > 0) {
                for (const recording of recordings.data) {
                    await this.processNote(recording, voiceNotesDir, false, '', unsyncedCount);
                }
                console.log(`Synced ${recordings.data.length} recordings from Voice Notes.`);
                const maxTs = (_c = RecordingUtility.getLatestNote(recordings.data)) === null || _c === void 0 ? void 0 : _c.updated_at;
                if (maxTs) {
                    this.settings.lastSyncedNoteUpdatedAt = new Date(maxTs).toISOString();
                }
                await this.saveSettings();
            }
            new obsidian.Notice(`Voicenotes Sync complete. ${unsyncedCount.count ? unsyncedCount.count + ' recordings were not synced due to excluded tags.' : ''} `);
        }
        catch (error) {
            console.error(error);
            if (Object.prototype.hasOwnProperty.call(error, 'status')) {
                // Only clear token if it's an authentication error (401)
                if (error.status === 401) {
                    this.settings.token = undefined;
                    await this.saveSettings();
                    new obsidian.Notice(`Login token was invalid, please try logging in again.`);
                }
                else {
                    new obsidian.Notice(`Error occurred syncing some notes to this vault.`);
                }
            }
            else {
                new obsidian.Notice(`Error occurred syncing some notes to this vault.`);
            }
        }
    }
}

module.exports = VoiceNotesPlugin;


/* nosourcemap */